-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 23:59:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `razonSocial` VARCHAR(255) NULL,
  `CUIT` VARCHAR(20) NULL,
  `mail` VARCHAR(45) NULL,
  `clientecol` VARCHAR(255) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cliente_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente_servicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente_servicio` (
  `idClienteServicio` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NULL,
  `servicio_id` INT NULL,
  `cliente_idCliente` INT NOT NULL,
  `servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`idClienteServicio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `especialidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `incidente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `incidente` (
  `idIncidente` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(255) NULL,
  `fechaEstimada` VARCHAR(255) NULL,
  `fechaHasta` VARCHAR(255) NULL,
  `consideraciones` VARCHAR(255) NULL,
  `cliente_id` INT NULL,
  `tecnico_id` INT NULL,
  `tecnico_idTecnico` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `resuelto` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idIncidente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `incidente_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidente_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `incidente_detalle` (
  `idIncidenteDetalle` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `incidente_id` INT NULL,
  `servicio_id` INT NULL,
  `tipoProblema_id` INT NULL,
  `servicio_idServicio` INT NOT NULL,
  `tipoProblema_idTipoProblema` INT NOT NULL,
  `incidente_idIncidente` INT NOT NULL,
  PRIMARY KEY (`idIncidenteDetalle`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `problema_especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `problema_especialidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `problema_especialidad` (
  `idProblemaEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `tipoProblema_id` INT NULL,
  `especialidad_id` INT NULL,
  `tipoProblema_idTipoProblema` INT NOT NULL,
  `especialidad_idEspecialidad` INT NOT NULL,
  PRIMARY KEY (`idProblemaEspecialidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tecnico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecnico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tecnico` (
  `idTecnico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NULL,
  `numTel` VARCHAR(255) NULL,
  PRIMARY KEY (`idTecnico`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tecnio_especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecnio_especialidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tecnio_especialidad` (
  `idTecnicoEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `tecnio_id` INT NOT NULL,
  `especialidad_id` INT NOT NULL,
  `especialidad_idEspecialidad` INT NOT NULL,
  `tecnico_idTecnico` INT NOT NULL,
  PRIMARY KEY (`idTecnicoEspecialidad`, `especialidad_idEspecialidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipoProblema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipoProblema` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipoProblema` (
  `idTipoProblema` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `tiempoEstimado` INT NULL,
  PRIMARY KEY (`idTipoProblema`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `rol_id` INT NULL,
  `rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
